version: '3'
services: 
  egg:
    build: .
    image: egg_server
    container_name: egg_server
    restart: always
    # ports: 
    #   - 127.0.0.1:7000:7000
    networks:
      - app-network
  nginx:
    image: nginx:stable-alpine
    container_name: egg_nginx    
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/cert:/etc/nginx/cert
      - ./logs/nginx:/var/log/nginx
    restart: always
    depends_on:
      - egg
    networks:
      - app-network
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_USER=root   #创建root用户
      - MYSQL_ROOT_PASSWORD=root #设置root用户密码
      - MYSQL_PASSWORD=12345678  
      - TZ=Asia/Shanghai # 设置时区
    volumes:
      - ./data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - app-network
  
  redis:
    image: redis
    container_name: egg_redis
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes: 
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports: 
      - "6379:6379"
    networks:
      - app-network
   

networks:
  app-network:
    driver: bridge 
# volumes:
#   certbot-etc:
#   certbot-var:
#   web-root:
#     driver: local
#     driver_opts:
#       type: none
#       device: /app
#       o: bind
     





    
      